### ISSUE TITLE
Display Target Info Independently

### ISSUE THREAD

**Issue by Axiarus** [kawaii/Moodles#14] opened 2024-03-02 19:43 UTC
When "Display Target Info Independently" is checked Moodles no longer show up. Meaning we can't use just a targets vanilla buffs/debuffs to add to our own UI currently.

**Comment by Axiarus** [comment] 2024-03-02 19:59
![2024-03-02-13_58_06](https://github.com/kawaii/Moodles/assets/147353181/c22e29cf-3f94-4fc4-b483-aa6c56e44cc3)

**Comment by kawaii** [comment] 2024-03-02 20:10
This is a duplicate of #2 and will be fixed later tonight.

**Closed by kawaii** 2024-03-02 20:10 UTC
