### ISSUE TITLE
Lock status effects on remote Mare users

### ISSUE THREAD

**Issue by Uriei** [kawaii/Moodles#3] opened 2024-03-01 15:51 UTC
I want to request that as other plugins that are used through mare, they lock all the configurations from those players so you can not edit them, if they are paired through mare, I know that only the person that sets the debuff will see it, but that won't prevent misuse for harassment of another players, I think that locking the status of a remote pair on mare is necessary.

**Comment by kawaii** [comment] 2024-03-01 16:00
It should already totally prevent application of any kind of Moodle to a character you are synced with, but I didn't actually have time to test that before the Mare update. I've just confirmed it's not working as intended and I'll fix it in the update later tonight.

**Comment by NevendyND** [comment] 2024-03-01 16:06
may i add something to it?
You can also put buffs on other Players that are not linked, but can't remove it from them after adding it to them.
It only could be removed after closing Game.

**Comment by kawaii** [comment] 2024-03-01 21:14
Partially resolved in 800cbfb2decefc1298651394e87a9781c7ddacf0.

Users who you are paired with and _do_ have their own Moodles applied will no longer be able to have your own Moodles put on them locally. Users who you are paired with and _don't_ have their own Moodles are still subject to this due to a limitation in the information Mare has about characters around you. It's possible we can fully fix this issue with some work from Mare's dev to support this use case.

**Closed by kawaii** 2024-03-01 21:14 UTC
Labels: bug
